//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekaH_server.App_DBHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class discussion
    {
        public long id { get; set; }
        public Nullable<long> assignmentID { get; set; }
        public string content { get; set; }
    
        public virtual assignment assignment { get; set; }
    }
}
