//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekaH_server.App_DBHandler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ekahEntities11 : DbContext
    {
        public ekahEntities11()
            : base("name=ekahEntities11")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointment> appointments { get; set; }
        public virtual DbSet<assignment> assignments { get; set; }
        public virtual DbSet<authentication> authentications { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<member_type> member_type { get; set; }
        public virtual DbSet<officehour> officehours { get; set; }
        public virtual DbSet<professor_info> professor_info { get; set; }
        public virtual DbSet<student_info> student_info { get; set; }
        public virtual DbSet<studentcourse> studentcourses { get; set; }
        public virtual DbSet<submission> submissions { get; set; }
        public virtual DbSet<discussion> discussions { get; set; }
    }
}
