//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekaH_server.App_DBHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentcourse
    {
        public int id { get; set; }
        public string courseID { get; set; }
        public string studentID { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual student_info student_info { get; set; }
    }
}
