//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ekaH_server.App_DBHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class submission
    {
        public long id { get; set; }
        public long assignmentID { get; set; }
        public string studentID { get; set; }
        public Nullable<int> grade { get; set; }
        public byte[] submissionContent { get; set; }
        public Nullable<System.DateTime> submissionDateTime { get; set; }
        public string submissionFileName { get; set; }
    
        public virtual assignment assignment { get; set; }
        public virtual student_info student_info { get; set; }
    }
}
